version: 2

sources:
  - name: mci_data            # this is the source name used in dbt
    database: KS_DEV          # Snowflake database
    schema: MCI_DATA          # Snowflake schema
    tables:
      - name: CSAT
      - name: IVR
      - name: SUBEASE
      - name: DIM_BRAND 

models:
  - name: dim_customer
    description: "Customer dimension table"
  - name: control_table_update
    description: "Update CONTROL_TABLE with latest max dates"